# Generated by Django 4.2.7 on 2023-12-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AddTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200)),
                ('CategoryIsFor', models.ManyToManyField(to='AddTask.taskmodel')),
            ],
        ),
    ]
