# Generated by Django 4.2.7 on 2023-12-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddCategory', '0002_remove_addcategory_categoryisfor'),
        ('AddTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(to='AddCategory.addcategory'),
        ),
    ]
