# Generated by Django 4.2.7 on 2023-12-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Bio', models.TextField()),
                ('Phone_Number', models.CharField(max_length=12)),
            ],
        ),
    ]
