# Generated by Django 4.2.7 on 2023-12-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0002_alter_musician_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumName', models.CharField(max_length=100)),
                ('releaseDate', models.DateTimeField()),
                ('Musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
                ('Rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='album.ratings')),
            ],
        ),
    ]
