# Generated by Django 4.2.7 on 2023-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_rating_alter_album_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='releaseDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
