# Generated by Django 4.2.7 on 2023-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musician_phonenumber'),
        ('album', '0003_alter_album_releasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Musician',
        ),
        migrations.AddField(
            model_name='album',
            name='Musician',
            field=models.ManyToManyField(to='musician.musician'),
        ),
    ]
