# Generated by Django 4.2.7 on 2023-12-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carModel', '0003_addcar_price_addcar_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcar',
            name='author',
        ),
    ]
