# Generated by Django 4.2.7 on 2023-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Posts/media/uploads/'),
        ),
    ]
